#!/usr/bin/env node
/**
 * Generate `renderer/i18n.js` from the locale bundles in `src/i18n/locales/`.
 *
 * The renderer loads plain <script> files (no bundler), so it can't `import`
 * JSON. This emits a self-contained file that embeds every locale bundle and
 * exposes `window.i18n` ({ setLocale, getLocale, t, locales, localeMeta }).
 *
 * SOURCE OF TRUTH = the JSON files. Never hand-edit renderer/i18n.js. Runs as
 * part of `npm run compile` (and `npm start` / smoke / dist by extension).
 */
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const localesDir = join(root, 'src', 'i18n', 'locales');
const out = join(root, 'renderer', 'i18n.js');

const bundles = {};
for (const f of readdirSync(localesDir)) {
  if (!f.endsWith('.json')) continue;
  const code = f.replace(/\.json$/, '');
  bundles[code] = JSON.parse(readFileSync(join(localesDir, f), 'utf8'));
}
const codes = Object.keys(bundles).sort((a) => (a === 'en' ? -1 : 1));

const banner = `/* AUTO-GENERATED by scripts/gen-i18n.mjs from src/i18n/locales/*.json — DO NOT EDIT.\n   Edit the JSON locale files, then run \`npm run gen-i18n\` (runs in \`npm run compile\`). */`;

const body = `${banner}
(function () {
  var BUNDLES = ${JSON.stringify(bundles, null, 0)};
  var LOCALES = ${JSON.stringify(codes)};
  var current = 'en';
  function normalize(loc) {
    var s = (loc || '').toLowerCase();
    if (s.indexOf('es') === 0) return 'es';
    if (s.indexOf('pt') === 0) return 'pt-br';
    return 'en';
  }
  function setLocale(loc) { current = normalize(loc); return current; }
  function getLocale() { return current; }
  function localeMeta() {
    return LOCALES.map(function (code) {
      var m = (BUNDLES[code] && BUNDLES[code].$meta) || {};
      return { code: code, name: m.name || code, nativeName: m.nativeName || code };
    });
  }
  function t(key, vars) {
    var b = BUNDLES[current] || BUNDLES.en;
    var s = b[key];
    if (s === undefined) s = BUNDLES.en[key];
    if (s === undefined) return key;
    if (vars) s = s.replace(/\\{(\\w+)\\}/g, function (_, k) { return vars[k] !== undefined ? String(vars[k]) : '{' + k + '}'; });
    return s;
  }
  window.i18n = { setLocale: setLocale, getLocale: getLocale, normalize: normalize, localeMeta: localeMeta, locales: LOCALES, t: t };
})();
`;

writeFileSync(out, body);
console.log('i18n generated →', out, '(' + codes.join(', ') + ')');
